name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: windows-2019 # windows-latest  # .NET Framework typically runs on Windows

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .NET Framework
      uses: microsoft/setup-msbuild@v1 # actions/setup-dotnet@v2
      #with:
        #dotnet-version: 4.x  # Specify the .NET Framework version
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore Dependencies
      run: nuget restore AtmTransaction.sln

    - name: Build
      run: msbuild AtmTransaction.sln -t:rebuild -property:Configuration=Release

# Add additional steps as needed for deployment, code analysis, etc.
